name: Generate JSON and Deploy to Github Pages

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: node build/generatePhotos.js
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          FLICKR_USER_ID: ${{ secrets.FLICKR_USER_ID }}
      - run: |
          git config user.name "mendhak"
          git config user.email "mendhak@users.noreply.github.com"
          git add data/photos.json
          git commit -m "Update photos.json" || exit 0
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: regenerate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5