name: Generate JSON and Deploy to Github Pages

on:
  workflow_dispatch:

  schedule:
    - cron: '30 5 * * *' # Runs every day at 05:30 AM 


jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0

        with:
          node-version: '24'
      - run: node build/generatePhotos.js
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          FLICKR_USER_ID: ${{ secrets.FLICKR_USER_ID }}
      - run: |
          git config user.name "mendhak"
          git config user.email "mendhak@users.noreply.github.com"
          git add data/photos.json
          git commit -m "Update photos.json" || exit 0
          git push

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: regenerate
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5